spring:
  datasource:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.101.57.147:3306/gm_springboot_layui?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      slave:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://129.211.63.133:3306/gm_springboot_layui?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
server:
  port: 8082
  tomcat:
      max-http-header-size: 8192
